/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Jackie Chan Stuntmaster)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8002601Cu
#define func_8002601C BootEntry  /* alias */
